routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'IndexController@index', 'as' => 'home']);
Route::resource('users', 'UsersController');
Route::resource('companies', 'CompaniesController');

app/Models/Users.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

    /**
     * App\Models\Users
     *
     * @property int $id
     * @property string $name
     * @property string $email
     * @property int $company_id
     * @property-read Companies $company
     * @property \Carbon\Carbon|null $created_at
     * @property \Carbon\Carbon|null $updated_at
     */

class Users extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'users';


    protected $fillable = ['name', 'email', 'company_id'];

    public function company()
    {
        return $this->hasOne(Companies::class, 'id', 'company_id');
    }

    public static function getList($limit = 10)
    {
        $result = Users::with('company');
        $result->latest();
        $result = $result->paginate($limit);
        return $result;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UsersRequest;
use App\Models\Companies;
use App\Models\Users;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = Users::getList();
        return view('users.index',
            [
                'users' => $users
            ]);
    }

    public function create()
    {
        $companies = Companies::getList();
        return view('users.create', [
            'companies' => $companies
        ]);
    }

    public function store(Request $request)
    {
        $messages = [
            'required' => 'Поле :attribute обязательное для заполнения',
            'unique' => ':attribute должен быть уникальным',
        ];


        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'email' => [
                'required',
                Rule::unique('users')
            ],
            'company_id' => 'required|integer'
        ], $messages);

        if($validator->fails()){
            $errors = $validator->errors();
            return [
                'success' => false,
                'response' => $errors->first()
            ];
        }
        $form = new Users();
        $form->fill($request->all());
        try {
            $form->save();
            return [
                'success' => true,
                'reload' => true
            ];

        } catch (\Exception $exception) {

            return [
                'success' => false,
                'response' => __('feedback::general.message-false'),
            ];

        };
    }

    public function edit(Users $user)
    {

        $companies = Companies::getList();
        return view('users.update', [
            'user' => $user,
            'companies' => $companies
        ]);
    }

    public function update(Request $request, Users $user)
    {
        $messages = [
            'required' => 'Поле :attribute обязательное для заполнения',
            'unique' => ':attribute должен быть уникальным',
        ];


        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'email' => [
                'required',
                Rule::unique('users')->whereNot('email', $user->email)
            ],
            'company_id' => 'required|integer'
        ], $messages);

        if($validator->fails()){
            $errors = $validator->errors();
            return [
                'success' => false,
                'response' => $errors->first()
            ];
        }

        $user->fill($request->input());
        try {
            $user->save();
            return [
                'success' => true,
                'reload' => true
            ];

        } catch (\Exception $exception) {

            return [
                'success' => false,
                'response' => __('feedback::general.message-false'),
            ];

        };
    }

    public function destroy(Users $user)
    {
        $user->forceDelete();
        return [
            'success' => true
        ];
    }
}

resources/views/users/create.blade.php
<form method="post" data-ajax="{{route('users.store')}}">
    <div class="form-group">
        <label for="recipient-name" class="col-form-label">ФИО *</label>
        <input name="name" type="text" class="form-control" required id="recipient-name">
    </div>
    <div class="form-group">
        <label for="recipient-email" class="col-form-label">Email *</label>
        <input name="email" required type="text" class="form-control" id="recipient-email">
    </div>
    <div class="form-group">
        <label for="message-company" class="col-form-label">Компания *</label>
        <select class="form-control" name="company_id" id="message-company" required>
            <option value="">Укажите компанию</option>
            @foreach($companies as $company)
                <option value="{{$company->id}}">{{$company->name}}</option>
            @endforeach
        </select>
    </div>
    {{csrf_field()}}
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
    </div>
</form>

resources/views/users/index.blade.php
@extends('layouts.main')
@section('content')
    <div>
        <nav class="navbar navbar-light bg-light">
            <div class="mr-2">
                <div class="btn-group">
                    <h1>Пользователи</h1>

                </div>
            </div>
            <div class="mr-2">
            <a href="{{route('home')}}" type="button" class="btn btn-primary">На главную</a>
            </div>
            <div class="mr-sm-2">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" href="{{route('users.create')}}" data-title="Добавление нового пользователя">Добавить</button>
            </div>
        </nav>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">ФИО</th>
                <th scope="col">Email</th>
                <th scope="col">Компания</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                        <th scope="row">{{$user->id}}</th>
                        <td>{{$user->name}}</td>
                        <td>{{$user->email}}</td>
                        <td>{{$user->company->name}}</td>
                        <td>
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" data-title="Редактирование" href="{{route('users.edit', $user->id)}}">
                                <span class="oi oi-pencil"></span>
                            </button>
                            <button type="button" class="btn btn-danger" data-href="{{route('users.destroy', $user->id)}}" data-toggle="modal" data-target="#confirm-delete">
                                <span class="oi oi-delete"></span>
                            </button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{$users->links()}}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Подтвердите действие
                </div>
                <div class="modal-body">
                    Вы действительно хотите удалить запись?
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger btn-ok">Да</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/update.blade.php
<form method="POST" data-ajax="{{route('users.update', [$user->id])}}">
    @method('PUT')
    <div class="form-group">
        <label for="recipient-name" class="col-form-label">ФИО *</label>
        <input value="{{$user->name}}" name="name" type="text" class="form-control" required id="recipient-name">
    </div>
    <div class="form-group">
        <label for="recipient-email" class="col-form-label">Email *</label>
        <input value="{{$user->email}}" name="email" required type="text" class="form-control" id="recipient-email">
    </div>
    <div class="form-group">
        <label for="message-company" class="col-form-label">Компания *</label>
        <select class="form-control" name="company_id" id="message-company" required>
            <option value="">Укажите компанию</option>
            @foreach($companies as $company)
                <option  {{$user->company_id == $company->id ? 'selected' : ''}} value="{{$company->id}}">{{$company->name}}</option>
            @endforeach
        </select>
    </div>
    {{csrf_field()}}
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
    </div>
</form>