routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses' => 'IndexController@index', 'as' => 'home']);
Route::resource('users', 'UsersController');
Route::resource('companies', 'CompaniesController');

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompaniesRequest;
use App\Models\Companies;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class CompaniesController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Companies::getList();
        return view('companies.index',
            [
                'companies' => $companies
            ]);
    }

    public function create()
    {
        $companies = Companies::getList();
        return view('companies.create', [
            'companies' => $companies
        ]);
    }

    public function store(Request $request)
    {
        $messages = [
            'required' => 'Поле :attribute обязательное для заполнения',
        ];


        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'quota' => 'required'
        ], $messages);

        if($validator->fails()){
            $errors = $validator->errors();
            return [
                'success' => false,
                'response' => $errors->first()
            ];
        }
        $form = new Companies();
        $form->fill($request->all());
        try {
            $form->save();
            return [
                'success' => true,
                'reload' => true
            ];

        } catch (\Exception $exception) {

            return [
                'success' => false,
                'response' => __('feedback::general.message-false'),
            ];

        };
    }

    public function edit(Companies $company)
    {
        return view('companies.update', [
            'company' => $company,
        ]);
    }

    public function update(Request $request, Companies $company)
    {
        $messages = [
            'required' => 'Поле :attribute обязательное для заполнения',
        ];


        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'quota' => 'required'
        ], $messages);

        if($validator->fails()){
            $errors = $validator->errors();
            return [
                'success' => false,
                'response' => $errors->first()
            ];
        }

        $company->fill($request->input());
        try {
            $company->save();
            return [
                'success' => true,
                'reload' => true
            ];

        } catch (\Exception $exception) {

            return [
                'success' => false,
                'response' => __('feedback::general.message-false'),
            ];

        };
    }

    public function destroy(Companies $company)
    {
        $company->forceDelete();
        return [
            'success' => true
        ];
    }
}

resources/views/companies/create.blade.php
<form method="post" data-ajax="{{route('companies.store')}}">
    <div class="form-group">
        <label for="recipient-name" class="col-form-label">Наименование *</label>
        <input name="name" type="text" class="form-control" required id="recipient-name">
    </div>
    <div class="form-group">
        <label for="recipient-name" class="col-form-label">Quota (MB) *</label>
        <input name="quota" type="text" class="form-control" required id="recipient-name">
    </div>
    {{csrf_field()}}
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
    </div>
</form>

resources/views/companies/index.blade.php
@extends('layouts.main')
@section('content')
    <div>
        <nav class="navbar navbar-light bg-light">
            <div class="mr-2">
                <div class="btn-group">
                    <h1>Компании</h1>

                </div>
            </div>
            <div class="mr-2">
            <a href="{{route('home')}}" type="button" class="btn btn-primary">На главную</a>
            </div>
            <div class="mr-sm-2">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" href="{{route('companies.create')}}" data-title="Добавление">Добавить</button>
            </div>
        </nav>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">ФИО</th>
                <th scope="col">Quota</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
                @foreach($companies as $company)
                    <tr>
                        <th scope="row">{{$company->id}}</th>
                        <td>{{$company->name}}</td>
                        <td>{{$company->quota_formatted}}</td>
                        <td></td>
                        <td>
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#myModal" data-title="Редактирование" href="{{route('companies.edit', $company->id)}}">
                                <span class="oi oi-pencil"></span>
                            </button>
                            <button type="button" class="btn btn-danger" data-href="{{route('companies.destroy', $company->id)}}" data-toggle="modal" data-target="#confirm-delete">
                                <span class="oi oi-delete"></span>
                            </button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        {{$companies->links()}}
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Подтвердите действие
                </div>
                <div class="modal-body">
                    Вы действительно хотите удалить запись?
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger btn-ok">Да</a>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/update.blade.php
<form method="POST" data-ajax="{{route('companies.update', [$company->id])}}">
    @method('PUT')
    <div class="form-group">
        <label for="recipient-name" class="col-form-label">Наименование *</label>
        <input value="{{$company->name}}" name="name" type="text" class="form-control" required id="recipient-name">
    </div>
    <div class="form-group">
        <label for="recipient-name" class="col-form-label">Quota (MB) *</label>
        <input value="{{$company->quota}}" name="quota" type="text" class="form-control" required id="recipient-name">
    </div>
    {{csrf_field()}}
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
    </div>
</form>